### ISSUE TITLE
'NoneType' object has no attribute 'lower' error while writing report.

### ISSUE THREAD

**Issue by Cyoung02** [niemasd/ViReport#13]
All parts of the pipeline seem to be working! All that's left is the final report generation, where I get this error:
![image](https://user-images.githubusercontent.com/46090395/79291040-714de500-7e82-11ea-908b-94cfcd95c029.png)
ViReport was run as follows: 
```
./ViReport.py -s ../Ebola_Sequences.fasta -t ../Sample_Times.tsv -o ~/Desktop/NiemaLab/testingViReport/Analysis/PhyloTools/IQTree/ --continue_workflow -gz 
```
You can access all the files for this particular run [here](https://github.com/Cyoung02/ViReport-Ebola/tree/master/PhyloTools/IQTree).

**Comment by niemasd** [comment]
Can you try git pull to download the most recent updates? I made some changes today. If that doesn't fix it, I'll investigate

**Comment by Cyoung02** [comment]
No luck even with the new pull.

**Comment by niemasd** [comment]
Woops, great catch! My report-writing module wasn't handling the case where the user doesn't specify sample categories (e.g. country from which the sample was collected, or gender, or some other categorical information). Fixed in https://github.com/niemasd/ViReport/commit/469ff95de4b6006209a4fb4d9414851cddf05000
